#+TITLE: This Site

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../styles.css">

* This Site

In the past, I've used [[https://jekyllrb.com][Jekyll]] for static site generation. I found it okay... but not quite involved enough. Plus I don't know Ruby.

I also wrote a snippet engine to take formatted text and replace it with..whatever you want. I used it for HTML. That was a little too hands on.

Now I use [[https://orgmode.org][Org Mode]] for drafting and generation of HTML.

* Hosting

This site is currently hosted on GitHub Pages. I am thinking of changing this soon, for several reasons. I don't think Microsoft respects my privacy that much. This isn't an immediate concern, as I don't store anything sensitive on GitHub, but it a reason to not like my host. The second being that it gives me less flexibility on how I manage my site. I think a smaller host would give me more flexibility and negotiating ability for what services I run. These are all minor and vague concerns, but still on my mind.

* Site Design

I have several sources of inspiration for my layout.

- LaTeX Documents
- [[https://gwern.net][Gwern Branwen]]
- Various JS-free personal websites.
